version: 2
multi-ecosystem-groups:
  weekly-dependency-updates:
    assignees:
      - glektarssza
    labels:
      - Dependency
    commit-message:
      prefix: '[Dependabot] '
    pull-request-branch-name:
      separator: /
    schedule:
      interval: weekly
      day: wednesday
      time: '12:00'
      timezone: Canada/Mountain
updates:
  - directory: .github/workflows
    package-ecosystem: github-actions
    rebase-strategy: auto
    groups:
      production-version-updates:
        applies-to: version-updates
        dependency-type: production
      development-version-updates:
        applies-to: version-updates
        dependency-type: development
      production-security-updates:
        applies-to: security-updates
        dependency-type: production
      development-security-updates:
        applies-to: security-updates
        dependency-type: development
    multi-ecosystem-group: weekly-dependency-updates
    patterns:
      - '*'
