<?xml version="1.0" encoding="UTF-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <OutputPath>bin/$(Configuration)/Mods/mod</OutputPath>
        <RootNamespace>GlekTarssza.VintageStory.AFKMod</RootNamespace>
        <ProjectDir>$(MSBuildProjectDirectory)/src/</ProjectDir>
        <ImplicitUsings>disable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup Label="Implicit Usings">
        <Using Include="System" />
    </ItemGroup>
    <PropertyGroup>
        <UserPropsPath Condition="$(UserPropsPath) == ''">$([System.IO.Path]::GetFullPath($([System.IO.Path]::Combine($(MSBuildProjectDirectory), '../user.props')))) </UserPropsPath>
    </PropertyGroup>
    <Target Name="PrintVars">
        <Message Text="UserPropsPath -> $(UserPropsPath)" Importance="High" />
        <Message Text="UserPropsPath::Exists -> $([System.IO.Path]::Exists($(UserPropsPath)))" Importance="High" />
    </Target>
    <Import Condition="Exists($(UserPropsPath))" Project="$(UserPropsPath)" />
    <ItemGroup>
        <Reference Include="VintagestoryAPI">
            <HintPath>$(VintageStoryInstallPath)/VintagestoryAPI.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="VSSurvivalMod">
            <HintPath>$(VintageStoryInstallPath)/Mods/VSSurvivalMod.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="VSEssentials">
            <HintPath>$(VintageStoryInstallPath)/Mods/VSEssentials.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Newtonsoft.Json">
            <HintPath>$(VintageStoryInstallPath)/Lib/Newtonsoft.Json.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="0Harmony">
            <HintPath>$(VintageStoryInstallPath)/Lib/0Harmony.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="VintagestoryLib">
            <HintPath>$(VintageStoryInstallPath)/VintagestoryLib.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>
    <ItemGroup>
        <Content Include="modinfo.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
    <ItemGroup>
        <Content Include="modicon.png" Condition="Exists('modicon.png')">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
</Project>
