# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test
on:
  workflow_call:
    inputs:
      ref:
        description: |
          The Git reference from which to clone the project.

          This can be any valid Git commit-ish (e.g. a SHA, a ref, a tag, and so
          on).

          Defaults to the SHA that caused the workflow to be triggered. If that
          is unavailable the fully formed reference of the branch or tag that
          triggered the workflow is used. If that is unavailable the repository
          default branch is used.
        type: string
        required: false
        default: ${{github.sha || github.ref || github.event.repository.default_branch}}
      build-config:
        description: |
          The configuration to build.

          Valid options are:
           * "debug"
           * "release"
        type: string
        required: true
      upload-coverage-artifacts:
        description: |
          Whether to upload the coverage artifacts.
        type: boolean
        required: false
        default: false
      artifact-retention-days:
        description: |
          The duration, in days, to retain artifacts for.

          Defaults to `0` which defaults to the value configured for the
          repository.
        type: number
        required: false
        default: 0
    secrets:
      github-token:
        description: |
          The token to use for making authenticated requests to the GitHub API.
        required: true
      reportgenerator-license:
        description: |
          The license key to use when calling the report generator tool.
        required: false
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      # -- To clone repository
      contents: read
      # -- To write coverage reports
      code-quality: write
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{inputs.ref}}
          lfs: true
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
      - id: setup-dotnet
        name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json
          cache: true
          cache-dependency-path: |
            ${{github.workspace}}/AFKMod/packages.lock.json
            ${{github.workspace}}/CakeBuild/packages.lock.json
      - id: download-vintage-story
        name: Download Vintage Story
        run: |
          mkdir -p ${{github.workspace}}/vs_install/
          wget https://cdn.vintagestory.at/gamefiles/stable/vs_client_linux-x64_1.22.3.tar.gz -O ${{github.workspace}}/vs_install/vs_client_linux-x64_1.22.3.tar.gz
          tar -C ${{github.workspace}}/vs_install/ -xvzf ${{github.workspace}}/vs_install/vs_client_linux-x64_1.22.3.tar.gz
          cat > user.props <<HEREDOC
          <?xml version="1.0" encoding="UTF-8"?>
          <Project>
              <PropertyGroup>
                  <VintageStoryInstallPath>${{github.workspace}}/vs_install/vintagestory/</VintageStoryInstallPath>
              </PropertyGroup>
          </Project>
          HEREDOC
          rm ${{github.workspace}}/vs_install/vs_client_linux-x64_1.22.3.tar.gz
      - id: install-reportgenerator
        name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool
      - id: restore-dependencies
        name: Restore dependencies
        run: dotnet restore
      - id: build
        name: Build
        run: ${{github.workspace}}/build.sh --configuration ${{inputs.build-config}}
      - id: test
        name: Test
        run: dotnet test --no-build --configuration ${{inputs.build-config}} --settings xplat_coverage.runsettings
      - id: check-should-generate-coverage-reports
        name: Check if should generate coverage reports
        run: |
          if [[ -n "$(find . -type f -iname "coverage.cobertura.xml")" ]]; then
            echo "has-coverage-reports=true" >> "${GITHUB_OUTPUT}"
          else
            echo "has-coverage-reports=false" >> "${GITHUB_OUTPUT}"
          fi
      - id: generate-html-report
        if: steps.check-should-generate-coverage-reports.outputs.has-coverage-reports
        name: Generate HTML report
        run: reportgenerator "-reports:**/coverage.cobertura.xml" "-targetdir:${{github.workspace}}/coverage/html" "-reporttypes:Html" "-title:G'lek's Vintage Story AFK Mod Code Coverage Report" "-assemblyfilters:-*Tests" "-license:${{secrets.reportgenerator-license}}"
      - id: generate-dark-html-report
        if: steps.check-should-generate-coverage-reports.outputs.has-coverage-reports
        name: Generate dark HTML report
        run: reportgenerator "-reports:**/coverage.cobertura.xml" "-targetdir:${{github.workspace}}/coverage/html_dark" "-reporttypes:Html_Dark" "-title:G'lek's Vintage Story AFK Mod Code Coverage Report" "-assemblyfilters:-*Tests" "-license:${{secrets.reportgenerator-license}}"
      - id: generate-merged-report
        if: steps.check-should-generate-coverage-reports.outputs.has-coverage-reports
        name: Generate merged report
        run: reportgenerator "-reports:**/coverage.cobertura.xml" "-targetdir:${{github.workspace}}/coverage/merged" "-reporttypes:Cobertura" "-title:G'lek's Vintage Story AFK Mod Code Coverage Report" "-assemblyfilters:-*Tests" "-license:${{secrets.reportgenerator-license}}"
      - id: upload-coverage-reports
        name: Upload coverage reports
        if: steps.check-should-generate-coverage-reports.outputs.has-coverage-reports
        uses: actions/upload-code-coverage@v1
        with:
          file: ${{github.workspace}}/coverage/merged/Cobertura.xml
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
          label: G'lek's Vintage Story AFK Mod Code Coverage Report
          language: C#
          fail-on-error: true
      - id: upload-coverage-artifacts
        name: Upload coverage artifacts
        if: inputs.upload-coverage-artifacts && steps.check-should-generate-coverage-reports.outputs.has-coverage-reports
        uses: actions/upload-artifact@v7
        with:
          name: coverage-reports
          path: coverage
          if-no-files-found: warn
          include-hidden-files: true
          compression-level: 9
          retention-days: ${{inputs.artifact-retention-days}}
